### ISSUE TITLE
ReferenceError: c is not defined

### ISSUE THREAD

**Issue by jacbop** [s-yadav/FlakeId#3]
This code in flakeid.js
```
    const a = {
      b: c,
      d: 2
    }

    //const d = {...a};
```

is causing the following errors when trying to use in node.js
```
$ npm test

> digitizer-apex@11.10.0 test C:\Users\tom\code\digitizer-apex
> mocha --colors --recursive --require ts-node/register --watch-extensions ts "**/*spec.ts"


C:\Users\tom\code\digitizer-apex\node_modules\flakeid\lib\flakeid.js:68
        b: c,
           ^
ReferenceError: c is not defined
    at FlakeId.gen (C:\Users\tom\code\digitizer-apex\node_modules\flakeid\lib\flakeid.js:68:12)
    at Object.get (C:\Users\tom\code\digitizer-apex\src\util\mockId.ts:24:29)
    at Object.<anonymous> (C:\Users\tom\code\digitizer-apex\src\util\mockId.spec.ts:6:20)
    at Module._compile (module.js:643:30)
    at Module.m._compile (C:\Users\tom\code\digitizer-apex\node_modules\ts-node\src\index.ts:430:23)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\tom\code\digitizer-apex\node_modules\ts-node\src\index.ts:433:12)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at C:\Users\tom\code\digitizer-apex\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\tom\code\digitizer-apex\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (C:\Users\tom\code\digitizer-apex\node_modules\mocha\lib\mocha.js:576:10)
    at Object.<anonymous> (C:\Users\tom\code\digitizer-apex\node_modules\mocha\bin\_mocha:637:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! Test failed.  See above for more details.

```

This seems like cruft code that can be removed.

**Comment by s-yadav** [comment]
The PR for the fix was merged. Closing this issue.
